apiVersion: v1
kind: Service
metadata:
  name: frigate-cam01
  namespace: frigate
  labels:
    ryanb.tv/app: frigate
spec:
  selector:
    app.kubernetes.io/name: frigate-cam01
  ports:
  - name: http
    protocol: TCP
    port: 8096
    targetPort: http
