---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflared-secrets
  namespace: cloudflared
spec:
  encryptedData:
    CF_TOKEN: AgB5VxlUHzv7YZ3cwTqo2EtrIOQ3XA2Hkk6Bg3Y4Vusy9AHUZ3XTkIvpAFW/x6wcquuWlL6XRVAxm0UW8mU9YE8kd3ViVu/6dG+wU5siBUZ5TdOLjN0ixKv16a9uiJXRDvqw4+QefXTaQNvhUmglUYDwxZSwmoc1ZWvTkNMjL0JMYJfQuLdQ7+V/lrqhSRFfp7XxXR6/IfFkFMER/bKB/fSOKIr/W8zPFhJ1BsfY45J8a7WRCp02zyRfv6FZsWfofiuYrpelRQbCSJcwYWENGEjSBqr7yOIgYfVVy+ETFpBoilWUCHXJOlxBTgjCZuGNATTkPVIQM/nmp7T9TK6K9rZ8PjruNQQiLEgvYhZX7s6P/LyzDCi4QuGYWR+doiNb67CKVN2v+kGofxFNSFu5FFc8ujcTw7WJwJWzf6nV9wwK4DCt88GgavDNTNodhKK/HQY0x2Drl4F8MFgTuZVlhi7XiMeRscOx05/zOCwQdOIWf09VrC6BAm5l80LAPE3DI+k+PwNDOkiuhtVWUs9GqAH8Lp2bvW8mDLwdIwuNMmCDHAXb2Hp0CKDcxzmuEQ+7BGCYiiv+giJeufzTG1Ml6/0XfiAuXk4SKWY/F7UJ31CocBqqkIHbMaWqsH1I6JqFPqc5Qbl1vlr5MLgvMiXUWCJAyeXDGhiaubdRIeRMGvYSZ4uZHgZLkXckGAHCMHm1bewORxhYg1scEsuLrdAZtrvkyDVP2iPdgfcNwxYt0+AsYvzIMBfUVrvZpgIVBUvLHIycZBA6vu3i1we/N9ZXS7HbvQnBvzYIUsV2ZXlRkJOlTZdIXamlya4Cehi4zBIm6/C8RvQT+bZL1cbsAXrUJqff8brViED7Xh6mT79EJGiGOCJhTMv2y0d9Sxy2hwYZ0zUUKnNL5p3+9AS1I2m6opHBZHw7wEKSD4IHMF4JUv/fV4ydeS4O6QeC
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflared-secrets
      namespace: cloudflared
