apiVersion: v1
kind: Service
metadata:
  name: cloudflared
  namespace: cloudflared
  labels:
    mylabel/app: cloudflared
spec:
  selector:
    app.kubernetes.io/name: cloudflared
  ports:
  - name: prometheus
    protocol: TCP
    port: 9100
    targetPort: http