---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  dependsOn:
    - name: sealed-secrets # CloudFlare email
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./src/fluxcd/infra/cert-manager
  prune: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: infra-sealed-secrets
