---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-crds
  namespace: flux-system
spec:
  dependsOn: []
  path: ./src/fluxcd/infra/cert-manager-crds
  targetNamespace: cert-manager 
  # Standard Params:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: src-fluxcd-infra
  prune: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager-crds
  path: ./src/fluxcd/infra/cert-manager
  targetNamespace: cert-manager 
  # Standard Params:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: src-fluxcd-infra
  prune: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-assets
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
    - name: sealed-secrets
  path: ./src/fluxcd/infra/cert-manager-assets
  targetNamespace: cert-manager 
  # Standard Params:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: src-fluxcd-infra
  prune: true
