---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflared
  namespace: flux-system
spec:
  dependsOn:
    - name: sealed-secrets # CloudFlare API Token
    - name: prometheus # ServiceMonitors
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./src/fluxcd/infra/controllers/cloudflared
  prune: true