---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: datashim
  namespace: flux-system
spec:
  dependsOn:
    - name: sealed-secrets # CloudFlare API Token
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: homelab-foss
  path: ./src/fluxcd/infra/datashim
  prune: true
