---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-webhook-receiver
  namespace: flux-system
spec:
  dependsOn:
    - name: sealed-secrets
  path: ./src/fluxcd/infra/flux-webhook-receiver
  targetNamespace: flux-system 
  # Standard Params:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: src-fluxcd-infra
  prune: true
