---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-assets
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./src/fluxcd/infra/metallb-assets
  prune: true
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: bfdprofiles.metallb.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: bgpadvertisements.metallb.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: bgppeers.metallb.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: communities.metallb.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: ipaddresspools.metallb.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: l2advertisements.metallb.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: servicel2statuses.metallb.io
