---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb
    - name: longhorn
    - name: sealed-secrets
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./src/fluxcd/infra/prometheus
  prune: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: infra-sealed-secrets
