---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-crds
  namespace: flux-system
spec:
  dependsOn: []
  path: ./src/fluxcd/infra/prometheus-crds
  targetNamespace: prometheus 
  # Standard Params:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: homelab-foss
  prune: true
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: ServiceMonitor.monitoring.coreos.com

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb
    - name: longhorn
    - name: sealed-secrets
  path: ./src/fluxcd/infra/prometheus
  targetNamespace: prometheus 
  # Standard Params:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: homelab-foss
  prune: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-assets
  namespace: flux-system
spec:
  dependsOn:
    - name: prometheus
    - name: traefik
  path: ./src/fluxcd/infra/prometheus-assets
  targetNamespace: prometheus 
  # Standard Params:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: homelab-foss
  prune: true
