---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-assets
  namespace: flux-system
spec:
  dependsOn:
    - name: prometheus
    - name: traefik
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: homelab-foss
  path: ./src/fluxcd/infra/prometheus-assets
  prune: true
