---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sealed-secrets-crds
  namespace: flux-system
spec:
  dependsOn: []
  path: ./src/fluxcd/infra/sealed-secrets-crds
  # Standard Params:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: src-fluxcd-infra
  prune: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  dependsOn:
  - name: sealed-secrets-crds
  path: ./src/fluxcd/infra/sealed-secrets
  targetNamespace: sealed-secrets 
  # Standard Params:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: src-fluxcd-infra
  prune: true
