---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-crds
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./src/fluxcd/infra/traefik/crds
  prune: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  dependsOn:
    - name: traefik-crds
    - name: metallb # LoadBalancerIP
    - name: prometheus # LoadBalancerIP
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./src/fluxcd/infra/traefik
  prune: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-assets
  namespace: flux-system
spec:
  dependsOn:
    - name: traefik-crds
    - name: sealed-secrets
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./src/fluxcd/infra/traefik/assets
  prune: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: infra-sealed-secrets
