---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-crds
  namespace: flux-system
spec:
  dependsOn: []
  path: ./src/fluxcd/infra/traefik-crds
  # Standard Params:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: src-fluxcd-infra
  prune: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  dependsOn:
    - name: traefik-crds
    - name: metallb # LoadBalancerIP
    - name: prometheus # LoadBalancerIP
  path: ./src/fluxcd/infra/traefik
  # Standard Params:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: src-fluxcd-infra
  prune: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-assets
  namespace: flux-system
spec:
  dependsOn:
    - name: traefik
    - name: prometheus
    - name: sealed-secrets
    - name: cert-manager-assets
  path: ./src/fluxcd/infra/traefik-assets
  targetNamespace: traefik 
  # Standard Params:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: src-fluxcd-infra
  prune: true
