---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: frigate-hooks-pre
  namespace: frigate
spec:
  dependsOn:
    - name: s3-csi # minio-media
    - name: sealed-secrets-assets # minio-creds
  targetNamespace: frigate
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-resources
  prune: true
  path: ./src/fluxcd/apps/frigate/hooks-pre

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: frigate-assets
  namespace: frigate
spec:
  dependsOn:
    - name: frigate-hooks-pre
    - name: node-feature-discovery-hooks-post
  targetNamespace: frigate
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-resources
  prune: true
  path: ./src/fluxcd/apps/frigate/assets

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: frigate-hooks-post
  namespace: frigate
spec:
  dependsOn:
    - name: frigate-assets
    - name: longhorn-assets # PersistentVolumeClaim
    - name: node-feature-discovery-hooks-post # nvidia
  targetNamespace: frigate
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-resources
  prune: true
  path: ./src/fluxcd/apps/frigate/hooks-post
