---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: netbox
spec:
  interval: 24h
  url: https://charts.netbox.oss.netboxlabs.com/

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
spec:
  interval: 24h
  url: https://charts.bitnami.com/bitnami
