---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: talos-cloud-controller-manager
  namespace: kube-system
spec:
  interval: 24h
  type: "oci"
  url: oci://ghcr.io/siderolabs/charts

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: talos-cloud-controller-manager
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: talos-cloud-controller-manager
      version: "0.4.2"
      sourceRef:
        kind: HelmRepository
        name: talos-cloud-controller-manager
        namespace: kube-system
      interval: 12h
  values:
    # Deploy the Talos Cloud Controller Manager as a DaemonSet
    useDaemonSet: true

    # Tolerate all taints
    tolerations:
      - effect: NoSchedule
        operator: Exists

    # Logging details
    logVerbosityLevel: 4

    # Allow node CSR approval and cloud-node controllers
    enabledControllers:
      - cloud-node
      - node-csr-approval
      - node-ipam-controller