---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: "grafana"
spec:
  external:
    url: http://grafana.prometheus.svc.cluster.local # Grafana URL
    adminPassword:
      name: grafana-secrets
      key: user
    adminUser:
      name: grafana-secrets
      key: pass
