---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: infra-sealed-secrets
  namespace: flux-system
spec:
  encryptedData:
    domain: AgAC2JITmQMrWV5ITWTQsLo/alajW9nYsJegloJMg8UymEuhQVF0rB0Laj6sren0rduEIOpa4WePtgqbeXCaDf137Om4LOINo40AtQTmUZ4lxghPdgoIkYlJcnP5Ng5H7ZFWfVd2SavopdC7qGWvtqZOTS84kx3y3UIT/edEOSCz6vEUoEB7JRcSRQPUnsWCttJg1jX2ZzyMgbWbCgqnAhiAAp/v6aZUfh5ASzxXdO/KJqa3Dnp9nJWU3aXlyjRvr3nZ9vxKl3irWrSloZiBGHV5eOM1GAdO0TKvYhnQjLB6EZeACut8Jto5p2GxJDVfR9ScuP2fRiyrIMfERsQkyNv8zRfX/9OsbUACyorAbYMs2rdm+47S0B6eQmqKnY4D9F6OGCOGsDzte3DKe+yWaRIuBA1NhGMIcKPI993TtAdqQJaf065VS75N9QINDdX1T3YQ0N2wg30m2oOWHCQZ9zuFBimPNmiWxykMEwk7H43QYGz4xEhJMp01dXKEX+sAuOwKMu5//cKE/IjYIzcuw2F7j2ehpX+YEYwnTYIQUsut6qoLCPhu9MB5E+IlxONeIOI+5XPqzGB0KMRcfrhlgj9DHiXnygr7irDVt3B8z4R+3RclHstCfC3+t84cUZH/8o+Fv3sFeacr2qzF2fszbPlj96w9n6bDCeqRjHH7wqN9ZYWp4ECZRAbkXsS/4EgbjNk9Rf0bgdMrTQ==
    email: AgBPLkr9By96D52cg3i5mRDYUjkg8MY7AKd3kQ9F3mKSRR17BMZEOkZPIco9TfoWpb8IaF9sXZCmGxqfszbeClpkMA6Y7ZU+TziQTESYEaOCLJPnOud8aR+8yZ4Y/DIwJopR8jmCbATjVeDnRM1lY+XqUWNkagPuP0iDrSHaHwnYNF9EtOcT6U+hluHTAv62wwpcIXMt5da3ikJui2uMTu+7bpiCMtMDysNkg9yQ2Kz7Qd4t+DadV7moy+ki/OtHi9E2+3yskm+cTu54BUpF04qAEuN2g9MWqLBrXDm5IRGxlUE/oceOJPIDqUwY+3LAKWVaIzSFwDOH//qrcELVcCE2q+Vlq6NioYja3xNWrX+xVJohY4tIPoXSNICMN80wDNxkwUIjz2QSmik+RcewUpkcIhjae0aVfvnnVTgmyLzOxUXLIu4uQxzBj+qUr9GHtDjRKKcsn9/m/08CQ5zhYSlLpVhAvuG5qugnxnlfq+4zUvp/M2iRMUQLcAUWWWWd8aiBI6xvIo9tmeT7IuGDSgh9UXyLjYAhNRD6CoVC6Pa/CKmTnwZsoe3EClfCXTO38ps1U/ySGemYjkuU44pPngWUIzOn9qrOlsTUqBJkOkLkV4kPs5LN3Q1LyqMdsp1PFvjnSuCe0XGqkQqgTUvX7gS1/CJtdg3R3oxVxlGlKtRtpeYoBv7boUyHNt0u3aaNkY/K4Yows80KFt53I22i
    password: AgASLXFFcBXtswU9MawmnOnvI4iHEfFtw5Jw4jewp/ecgzYreN55v53rvY+TsOtqe6xhHPW0H0uP/EyOrrPoihIkqnktyt1R+XpL5fnqVKs7wkUwvAjWGI0TJw8f2tnPBKB6n0JkodXvxMheHQyDIWucAiAwvl6LZwgZz3GuGujxDSp8Es+93N1CrMhQAhjeGEhbhtomQrl7VwK18F5y7uvt7c1mAPFT1pP0E+NgInuG8lJYNJN5eRgTzfgs3Jb4b2CwKAlVijlVZ1Un7W6zq+9uM9cEtyXzouNm3sXqZW92AdINE8RY4VZAf0+EXzXe6Y6bGas0qIaKIeJ4tR2bAZL2VilRxosgFLz58RG8HuY4D7qRx5mYr7ihhQReqxKYgm82BZoySaweoDsvJ1ujEoWMxQnuXkSF9iPMhzv1C799IXW6+Sp20YloKcYTPkbuNOHUJgzHM++FDOpNs89agXQMZjd1X3JeEHcP/exdxkIOpzuK+Sto4Z3yBbPs6KfXNKLmUqrNXwNteMv89JCCmyrmHBg2R9laa4dQVue+TTL3LwuOhVKTXgtcjVNDEajreUm6XjpdqQ6aJVbis3IiKuHrhL7Iz+cmWGLle6n4fPc8D5BM+1aSicPAuqa5ZuqCPXcgxOhHaL85Tg0hvesKnqlzswZitFZZsD1ShFuq8WhkdwL2D/KLElI4PRfRufCyMGVUX/0I8rOgkQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: infra-sealed-secrets
      namespace: flux-system
    type: Opaque
