# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: netbox-hooks-pre
#   namespace: flux-system
# spec:
#   dependsOn: []
#   path: ./src/fluxcd/apps/netbox/hooks-pre
#   targetNamespace: netbox 
#   # Standard Params:
#   interval: 1h
#   retryInterval: 1m
#   timeout: 5m
#   sourceRef:
#     kind: GitRepository
#     name: flux-resources
#   prune: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: netbox-assets
  namespace: flux-system
spec:
  dependsOn:
    - name: traefik-assets
    - name: longhorn-assets
  path: ./src/fluxcd/apps/netbox/assets
  targetNamespace: netbox
  # Standard Params:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-resources
  prune: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: netbox-hooks-post
  namespace: flux-system
spec:
  dependsOn:
    - name: netbox-assets
    - name: sealed-secrets-assets
  path: ./src/fluxcd/apps/netbox/hooks-post
  targetNamespace: netbox 
  # Standard Params:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-resources
  prune: true
