---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: netbox-assets
  namespace: flux-system
spec:
  dependsOn:
    - name: longhorn-assets # PersistentVolume
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-resources
  prune: true
  path: ./src/fluxcd/apps/netbox/assets
  targetNamespace: netbox 

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: netbox-hooks-post
  namespace: flux-system
spec:
  dependsOn:
    - name: netbox-assets
    - name: traefik-hooks-post # IngressRoute
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-resources
  prune: true
  path: ./src/fluxcd/apps/netbox/hooks-post
  targetNamespace: netbox 
