---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/bitnami-labs/sealed-secrets/refs/heads/release/v0.27.1/helm/sealed-secrets/crds/bitnami.com_sealedsecrets.yaml
  - http://s3.ff.lan:9000/private/backup.yml # Internal HTTP server with sealed-secrets key to bootstrap