apiVersion: v1
kind: Secret
metadata:
  name: homelab-foss-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/ryanbtv/homelab-foss