---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./src/fluxcd/infra/controllers
  prune: true
  wait: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-controllers
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./src/fluxcd/infra/configs
  prune: true
  patches:
    # MetalLB Advertised Pool & BGP Peer
    - patch: |
        - op: replace
          path: /spec/addresses
          value: [10.1.50.128/27]
      target:
        kind: IPAddressPool
        name: services-pool
    - patch: |
        - op: replace
          path: /spec/myASN
          value: 65100
      target:
        kind: BGPPeer
        name: ff-icr01.lan
