---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-crds
  namespace: prometheus
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus-operator-crds
      version: "15.0.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
      interval: 12h