---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus
spec:
  interval: 24h
  url: https://prometheus-community.github.io/helm-charts

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
spec:
  interval: 24h
  url: https://grafana.github.io/helm-charts

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: grafana-operator
spec:
  interval: 10m
  url: oci://ghcr.io/grafana/helm-charts/grafana-operator
  ref:
    tag: v5.14.0
