---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secrets
  namespace: grafana
spec:
  encryptedData:
    pass: AgAfzFeQfsRKfyEz3px1TjhqRFL6SEp6iyWt5E9dJaNz1GnC5areHRnutWvDFFGVnd0q95ZbpiF8QKCiOMnhZe0b/CKYF1I4nK+kx+vJp81fiRT7vZm94/lpztThn3ey8qecBxTiEaIeyeEBcf9ewD78XwcoQh14nuzZ0jhb2S+XHJGT0eEMM+vIYh20tUsAM2i7y8a4PxbwAdKWkhfdrH0Hd0BOc9SXthC+cxMrzj1mJhH2W/K9nMuHaYJ+V3qxy9xmCeA1eCX/dtozxEkj7pczHPasYFdTKnBzOReKxr/tZFdn1SGOmwa0dyLiZFEWt1dKBlM7Tg9glVhZ8Zya/oi8DuWtpHR9gr+hPvE5VNabDA+WaDHPkq1D2/RPsgHfTG3iL5+VqOGsvZJYqh9TTBnIoUGrejEIoHcvjFd4C6uqhqcQE5AgSnWlVwXjvTyB+z4K4ZclZpvSrb50mdAV1C7jlECw1MS2awQCM9OtZYi00guK1FjCHTAck9rJj3RVmSdI6tLkXK59OAw1EUxUWzl02tkZhaDBEWhprYORBmi2kyZNypYLGtJo1kqs7/HgQ0TV3VrGVrnY9c6MRU2WarUvCw/XSyv4LDL8EKlWOdzmtywoc8nMo8TQnxci0dHp47tZbZtzQFZQE8J7p+eFYNDS1wOhS+49qhjY2Z3L9Klt9cwetqZeOTyGFY+5PteOFK3MMmuTCiaCqQ==
    user: AgAPKJle3a8KVn2KnY4ICNPy5qJYMGIHKH/6ASodwimfzvGgZ+htsWYHWQ0zxEqrJXDOwgQqmDiTD/W34RSsq0JddZMegsuZpMZYPc/k898pa8YgoAZ3tb2JFaTz7722LJHfZA6tvmuwBGYt4m+Yvx6apMvHEwZ4Bo3Om70cwJIE3OzjSaDSTDdLul9tFVpRDsSX9Cej52BxBrKpS3QFHyiWkYma0RuoObclyoK7bYODw1SZpItFi+VaSyVOr8nu4Lu758zov3rB8mdiJe2ClBDlsNaoZpzK0yU2BDfGrFNTY6WgPUAGikaI/O+v5OfzROiG35cOjQzrDxNB5BIf03uJ5mE7U7Ei1vo0Ei7pgyD0cY8gJ0pPS9FqdlmIuRgKfAcLNotxea+0HpF0G1bo7hx1FRCtuSPjkoO4o7o6/9PGvTEoQDkWpgsFdKlVQ+/Q0jLO3WuuHkGTw7eRZnvduaNW2ktzN+xUhcOPngXb0AaVtw8e5toQEsbfkqCQCcTYyRcuqVC0JWB3hQgAjb6kMMyQubU2u0XIaiU/nVfVbxYNDfEIaK4TUHVoVz9Mw2a+SDhd6hpPMJbmMpIbgygEAAc9/LcFC9jHPxdhwknOrzUwgoBcmZURa0Y3BHMkf8zgXo0XiCp/OYDpssFgD82JbbxCpUkH41NeMS7RJ5CMTdsXZEURbIjTRIDkdUSBAnHgRzyvtycTCQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secrets
      namespace: grafana
