---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-hooks-pre
  namespace: flux-system
spec:
  dependsOn:
    - name: flux-namespaces
  path: ./src/fluxcd/infra/longhorn/hooks-pre
  # Standard Params:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-resources
  prune: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-assets
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb-assets # LoadBalancerIP
    - name: longhorn-hooks-pre
  path: ./src/fluxcd/infra/longhorn/assets
  # Standard Params:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-resources
  prune: true

# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: longhorn-hooks-post
#   namespace: flux-system
# spec:
#   dependsOn:
#     - name: longhorn-assets
#   path: ./src/fluxcd/infra/longhorn/hooks-post
#   # Standard Params:
#   interval: 1h
#   retryInterval: 1m
#   timeout: 5m
#   sourceRef:
#     kind: GitRepository
#     name: flux-resources
#   prune: true
