---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  dependsOn:
    - name: metallb
      namespace: metallb
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: "1.7.1"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn-system
      interval: 12h
  values:
    service:
      ui:
        type: LoadBalancer
        loadBalancerIP: 10.1.50.129
    preUpgradeChecker:
      jobEnabled: false
    defaultSettings:
      allowCollectingLonghornUsageMetrics: false
      createDefaultDiskLabeledNodes: true # Disables auto-disk-provisioning since no nodes are labeled
      defaultDataLocality: best-effort
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      v2DataEngine: 1
      backupTarget: s3://backups@us-north/longhorn
      backupTargetCredentialSecret: minio-creds-longhorn-backups
    metrics:
      serviceMonitor:
        enabled: false # Will be set later via patch
  postRenderers:
    - kustomize:
        patches:
          - target:
              group: longhorn.io
              version: v1beta2
              kind: Node
              name: k8s01.prod
            patch: |
              - op: add
                path: /spec/disks
                value:
                  data:
                    allowScheduling: true
                    diskDriver: auto
                    diskType: block
                    evictionRequested: false
                    path: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_pve-scsi1
                    storageReserved: 0
                    tags:
