machine:
  network:
    interfaces:
      - interface: eth0
        vip:
          ip: 10.1.40.30 # Sets API VIP for controlplane nodes
  nodeLabels:
    node.kubernetes.io/exclude-from-external-load-balancers:
      $patch: delete