---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbox
  namespace: netbox
spec:
  interval: 30m
  chart:
    spec:
      chart: netbox
      version: 5.0.0-beta.124
      sourceRef:
        kind: HelmRepository
        name: netbox
        namespace: flux-system
      interval: 12h
  values:
    image:
      repository: ghcr.io/slothcroissant/docker-netbox
      tag: v4.1-3.0.2
      pullPolicy: IfNotPresent
    persistence: 
      enabled: false
    postgresql:
      enabled: false
    externalDatabase:
      host: netbox-postgresql
      password: mypassword
    redis:
      enabled: false
    tasksRedis:
      host: netbox-redis-master
      password: mypassword
    cachingRedis:
      host: netbox-redis-master
      password: mypassword

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: netbox
spec:
  interval: 30m
  chart:
    spec:
      chart: postgresql
      version: 16.0.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 12h
  values:
    fullnameOverride: netbox-postgresql
    auth:
      username: netbox
      postgresPassword: mypassword
      password: mypassword
      database: netbox
    volumePermissions:
      containerSecurityContext:
        runAsUser: 1000
    primary:
      persistence: 
        enabled: true

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: netbox
spec:
  interval: 30m
  chart:
    spec:
      chart: redis
      version: 20.2.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 12h
  values:
    fullnameOverride: netbox-redis
    auth:
      password: mypassword
    master:
      persistence:
        enabled: false
    replica:
      kind: DaemonSet
      persistence:
        enabled: false