---
apiVersion: datashim.io/v1alpha1
kind: Dataset
metadata:
  name: media
  namespace: jellyfin
spec:
  local:
    type: "COS"
    secret-name: "minio-creds-jellyfin-media" #Must be in same namespace (it's below)
    endpoint: "http://s3.ff.lan:9000"
    bucket: "media"
    readonly: "true"
    region: "us-north"