services:
  dockerio:
    image: docker.io/library/registry:2
      - REGISTRY_PROXY_REMOTEURL=https://registry-1.docker.io
  quayio:
    image: docker.io/library/registry:2
      - REGISTRY_PROXY_REMOTEURL=https://quay.io
  ghcrio:
    image: docker.io/library/registry:2
      - REGISTRY_PROXY_REMOTEURL=https://ghcr.io


REGISTRY_STORAGE: s3
REGISTRY_STORAGE_S3_ACCESSKEY: mystring
REGISTRY_STORAGE_S3_SECRETKEY: mystring
REGISTRY_STORAGE_S3_BUCKET: mystring
REGISTRY_STORAGE_S3_REGION: mystring
REGISTRY_HEALTH_STORAGEDRIVER_ENABLED: false