---
services:
  app:
    image: ghcr.io/koenkk/zigbee2mqtt:1.40.2
    environment:
    - TZ=America/Chicago
    volumes:
      - zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_ae9b2255f663ec1193514debee680de7-if00-port0:/dev/ttyACM0
    restart: always
    ports:
      - 8080:8080

volumes:
  zigbee2mqtt: