apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ryanb.tv-prod-cert
  namespace: traefik
spec:
  secretName: ryanb.tv-prod-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.ryanb.tv"
  dnsNames:
  - "*.ryanb.tv"
