---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blackbox-exporter
  namespace: prometheus
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      version: "9.0.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: prometheus
      interval: 12h
  values:
    replicas: 2
    config:
      modules:
        http:
          prober: http
          timeout: 5s
          http:
            valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
            follow_redirects: true
            preferred_ip_protocol: "ip4"
        icmp:
          prober: icmp
          icmp:
            preferred_ip_protocol: ip4
        tcp:
          prober: tcp
          tcp:
            preferred_ip_protocol: ip4
