apiVersion: v1
kind: Service
metadata:
  name: codeprojectai
spec:
  selector:
    app.kubernetes.io/name: codeprojectai
  ports:
  - name: http
    protocol: TCP
    port: 32168
    targetPort: http
  type: LoadBalancer
  loadBalancerIP: 10.1.50.134