---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-hooks-pre
  namespace: flux-system
spec:
  dependsOn: []
  path: ./src/fluxcd/infra/traefik/hooks-pre
  targetNamespace: traefik 
  # Standard Params:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-resources
  prune: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-assets
  namespace: flux-system
spec:
  dependsOn:
    - name: traefik
  path: ./src/fluxcd/infra/traefik/assets
  targetNamespace: traefik 
  # Standard Params:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-resources
  prune: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-hooks-post
  namespace: flux-system
spec:
  dependsOn:
    - name: traefik
  path: ./src/fluxcd/infra/traefik/traefik/hooks-post
  targetNamespace: traefik 
  # Standard Params:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-resources
  prune: true
