---
# Volume pre-created in Longhorn
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: jellyfin-pvc
    namespace: jellyfin
  csi:
    driver: driver.longhorn.io
    fsType: xfs
    volumeAttributes:
      numberOfReplicas: '4'
    volumeHandle: jellyfin
  persistentVolumeReclaimPolicy: Retain
  storageClaassName: longhorn-static
  volumeMode: Filesystem

---
# PVC for Volume pre-created in Longhorn
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-pvc
  namespace: jellyfin
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn-static
  volumeMode: Filesystem
  volumeName: jellyfin-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-pv
spec:
  capacity:
    storage: 250Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  claimRef: # To ensure no other PVCs can claim this PV
    name: jellyfin-media-pvc # Name of your PVC
    namespace: jellyfin
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/s3/media
  nodeAffinity: # TODO: Map affinity to host mounts availability 
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s01.prod
          - k8s02.prod
          - k8s03.prod
          - k8s04.prod
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-pvc
  namespace: jellyfin
spec:
  accessModes:
    - ReadOnlyMany # Supported options: ReadWriteMany / ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 250Gi # Ignored, required
  volumeName: jellyfin-media-pv # Name of your PV