apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vaultwarden
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`vault.ryanb.tv`)
      kind: Rule
      services:
        - name: vaultwarden
          kind: Service
          port: http
  tls: {}