---
# Volume pre-created in Longhorn
apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-cam04
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: frigate-cam04
    namespace: frigate
  csi:
    driver: driver.longhorn.io
    fsType: xfs
    volumeAttributes:
      numberOfReplicas: '4'
    volumeHandle: frigate-cam04
  persistentVolumeReclaimPolicy: Retain
  storageClaassName: longhorn-static
  volumeMode: Filesystem

---
# PVC for Volume pre-created in Longhorn
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-cam04
  namespace: frigate
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-static
  volumeMode: Filesystem
  volumeName: frigate-cam04

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-cam04-recordings-pv
spec:
  capacity:
    storage: 250Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  claimRef: # To ensure no other PVCs can claim this PV
    name: frigate-cam04-recordings-pvc # Name of your PVC
    namespace: frigate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/s3/frigate-cam04
  nodeAffinity: # TODO: Map affinity to host mounts availability 
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s01.prod
          - k8s02.prod
          - k8s03.prod
          - k8s04.prod
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-cam04-recordings-pvc
  namespace: frigate
spec:
  accessModes:
    - ReadOnlyMany # Supported options: ReadWriteMany / ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 250Gi # Ignored, required
  volumeName: frigate-cam04-recordings-pv # Name of your PV