apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-cam05-cm
  namespace: frigate
data:
  config.yml: |
    # yaml-language-server: $schema=http://cam05-nvr.ff.lan:5000/api/config/schema.json
    mqtt:
      host: emqx-listeners.emqx.svc.cluster.local
      port: 1883
      stats_interval: 60
      topic_prefix: cam05
      client_id: cam05

    database:
      path: /config/frigate.db

    objects:
      track:
        - person
        - bicycle
        - car
        - motorcycle
        - bus
        - dog
        - cat

    record:
      enabled: True
      retain:
        days: 7
        mode: all

    detect:
      enabled: True
      fps: 5

    detectors:
      deepstack:
        api_url: http://codeprojectai.codeprojectai.svc.cluster.local:32168/v1/vision/custom/ipcam-combined
        type: deepstack
        api_timeout: 1.0 # seconds

    snapshots:
      enabled: True

    ffmpeg:
      hwaccel_args: preset-nvidia-h264

    birdseye:
      enabled: False

    logger:
      default: info

    go2rtc:
      streams:
        cam05:
          - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.1.30.15:554/cam/realmonitor?channel=1&subtype=0
        cam05_sub:
          - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@10.1.30.15:554/cam/realmonitor?channel=1&subtype=1
      webrtc:
        candidates:
          - 10.1.50.145:8555
      homekit:
        cam05:  # same stream ID from streams list

    cameras:
      cam05:
        ffmpeg:
          inputs:
            - path: rtsp://127.0.0.1:8554/cam05
              input_args: preset-rtsp-restream-low-latency
              roles:
                - record
                - detect
