---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: frigate-cam07-pvc
  namespace: frigate
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-cam07-recordings-pv
spec:
  capacity:
    storage: 250Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  claimRef: # To ensure no other PVCs can claim this PV
    name: frigate-cam07-recordings-pvc # Name of your PVC
    namespace: frigate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/s3/frigate-cam07
  nodeAffinity: # TODO: Map affinity to host mounts availability 
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s01.prod
          - k8s02.prod
          - k8s03.prod
          - k8s04.prod
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-cam07-recordings-pvc
  namespace: frigate
spec:
  accessModes:
    - ReadOnlyMany # Supported options: ReadWriteMany / ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 250Gi # Ignored, required
  volumeName: frigate-cam07-recordings-pv # Name of your PV