---
apiVersion: datashim.io/v1alpha1
kind: Dataset
metadata:
  name: frigate-cam01-media
  namespace: frigate
spec:
  local:
    type: "COS"
    secret-name: "frigate-secrets" #Must be in same namespace
    endpoint: "http://s3.ff.lan:9000"
    bucket: "frigate"
    readonly: "false"
    region: "us-north"

---
apiVersion: datashim.io/v1alpha1
kind: Dataset
metadata:
  name: frigate-cam02-media
  namespace: frigate
spec:
  local:
    type: "COS"
    secret-name: "frigate-secrets" #Must be in same namespace
    endpoint: "http://s3.ff.lan:9000"
    bucket: "frigate"
    folder: "/cam02" 
    readonly: "false"
    region: "us-north"

---
apiVersion: datashim.io/v1alpha1
kind: Dataset
metadata:
  name: frigate-cam03-media
  namespace: frigate
spec:
  local:
    type: "COS"
    secret-name: "frigate-secrets" #Must be in same namespace
    endpoint: "http://s3.ff.lan:9000"
    bucket: "frigate"
    folder: "/cam03" 
    readonly: "false"
    region: "us-north"

---
apiVersion: datashim.io/v1alpha1
kind: Dataset
metadata:
  name: frigate-cam04-media
  namespace: frigate
spec:
  local:
    type: "COS"
    secret-name: "frigate-secrets" #Must be in same namespace
    endpoint: "http://s3.ff.lan:9000"
    bucket: "frigate"
    folder: "/cam04" 
    readonly: "false"
    region: "us-north"

---
apiVersion: datashim.io/v1alpha1
kind: Dataset
metadata:
  name: frigate-cam05-media
  namespace: frigate
spec:
  local:
    type: "COS"
    secret-name: "frigate-secrets" #Must be in same namespace
    endpoint: "http://s3.ff.lan:9000"
    bucket: "frigate"
    folder: "/cam05" 
    readonly: "false"
    region: "us-north"

---
apiVersion: datashim.io/v1alpha1
kind: Dataset
metadata:
  name: frigate-cam06-media
  namespace: frigate
spec:
  local:
    type: "COS"
    secret-name: "frigate-secrets" #Must be in same namespace
    endpoint: "http://s3.ff.lan:9000"
    bucket: "frigate"
    folder: "/cam06" 
    readonly: "false"
    region: "us-north"

---
apiVersion: datashim.io/v1alpha1
kind: Dataset
metadata:
  name: frigate-cam07-media
  namespace: frigate
spec:
  local:
    type: "COS"
    secret-name: "frigate-secrets" #Must be in same namespace
    endpoint: "http://s3.ff.lan:9000"
    bucket: "frigate"
    folder: "/cam07" 
    readonly: "false"
    region: "us-north"

---
apiVersion: datashim.io/v1alpha1
kind: Dataset
metadata:
  name: frigate-cam08-media
  namespace: frigate
spec:
  local:
    type: "COS"
    secret-name: "frigate-secrets" #Must be in same namespace
    endpoint: "http://s3.ff.lan:9000"
    bucket: "frigate"
    folder: "/cam08" 
    readonly: "false"
    region: "us-north"

---
apiVersion: datashim.io/v1alpha1
kind: Dataset
metadata:
  name: frigate-cam09-media
  namespace: frigate
spec:
  local:
    type: "COS"
    secret-name: "frigate-secrets" #Must be in same namespace
    endpoint: "http://s3.ff.lan:9000"
    bucket: "frigate"
    folder: "/cam09" 
    readonly: "false"
    region: "us-north"