---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frigate-secrets
  namespace: frigate
spec:
  encryptedData:
    FRIGATE_RTSP_PASSWORD: AgA2gLEFxLwbzcPQfuS7Wy/yNQjWsNiEdVr7VuxDKL52L4I5dIwNf3TWi339NsHK+VIsWZ3JQCkx7g3eBb9i6yRRndBtgL+QAllLrnED5Fm6/BwgE83IoILxxUzYrrhPmlG1Do5FcKnnDANv8pewFphCst1DeyTmi060kXOn21ndGg2MXtMgk747hn1798JpEy/doNdUeyRLOiQyonwUFdDNjf6+hRMvXRHXGv/70T0+vN1Ki4ikO0bf94jZQhu8VnIXUhMEueNF1JytM5Z27vdhjRAvPUiorDr3u2xyIQSEsD3XxAtVJDCIGM8FcY5UrzVXpytZzqHbyDsFkdRDpZrLS3hvk5HX55VqBFW8ZVjwJ5hioKSZeJbnThBJKpFNykNQ/TQU9Z8EXzAtKqd1O0luRuN1mezayvrOTb7TJBs8IRbw4aUhyVO2lTlm3uaSSBeaXA0Lwyh9YClV4EfOPkOQ88f6ThPA+INhYA0PyyBS23rWG2MDvAfgZ6lKZZ1sMhkwteExv2RB1rnsBI44UYPx+N8Mj7ieioK4YfYXyFcu+C7B7rmabEosPJ8F+R+5WdGLE0fQfs3SayHxfh4gfXGbrq8R90ZFpjGDuh13M0U+MNf9sKzy5rYG1m2drXB/JbaoNdObbgVzsN8Zk8Y6RdbXDMIHHrssGonhPLr7QX0h+O5bWkZafTv12vhOL1Y8WJwIrgp9FgDIlA==
  template:
    metadata:
      creationTimestamp: null
      name: frigate-secrets
      namespace: frigate
