---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frigate-secrets
  namespace: frigate
spec:
  encryptedData:
    accessKeyID: AgCg2/0LcbP9zVe066EVH5d1Th39CZUyvAAaKN1/+eB0KJdfWYb1MLJ4j1Fdj0Kd71zQmvLL2k1e/payTr7FeHhHsXiC442EVbYC93QFG1xTqynDSU6v6zaEA+HFCuLamLyBlLWmQL43irqiKHnGHp6Q3MAxU9khZ/zI/kjH55QdI61yKkJ/gj/7PwYOife7XHI4k3SjhE6JgLDwH4c6wTHnLAYFiQ7cT0tAeGaimZW7V4wLwu3X9cKhLs6l/CQlCh5O5vmXdmzZs7E6t1JZw/yGk1uerdlKwrh8B5Psy5+6UrHcxfEoZyym7PwXgBhhD+HjcD+TwYSQgZL8okiAHpGsSQ+0yGvoExmjXUaFu7Ar63ltyRJKm83YVLuHQtAyWlAjCjh6GO4k4dzlSaKT5jFP+GlQi1oo2iO3LBk/H9VB2Dvya17QW5IRGM9SNYgejPLm2ESPGx2Z3twrIuU2R3zT1cj4ICEok3CTtvD+CvTqg8IEEeeS+hcxc0H6x04Sx/hNGbTCVQyI76lK0n4Adf3xBMBMejz1SZ5/p3Odl2P8+Fb+/LGqhh3rx/bQW6xKstG4seUJgJC6YPUUt9EY3a9hCnrx+mh5vhoB2PTEuozq9u0D/2twU1j9XjGsuLfO32M7nKIFYURLTy1tkNfz+xBi66ARFFENMdOFgWUTwVxcxQa9liCBdmEsV9OdpOIVzGVcefyZlg==
    secretAccessKey: AgBVBdQHnzAZwfsiZwV5Td7lPQLTwr4vcwjvgcSCHe2vKQK1xlsik+j2XCmZj754FEAOQ/gKllp/8Kp++7FWPo46tqxPiBqS3T8xHGQR0DIJHalxvK3kEj/eMiA+Wpypz8vQkYjLP7/wZCwZWgPjkHlIh5mbqo0pt6pIQQIP3mNSIWU+YiUHq92oJRmrxwyT3GJpUg6v4wnzp7eZIheuFgLaRH6DfAdZJyoDJdB0h+rnJd5/LYgg0e0jQJDipxLCgMKhNhpieeIYKqvQ29G2verrvOHRhwSpeIGyD/BOW/cDBvP17v0lzsoDmXAAjLvXj1Jliw6Udi/AnQQpPJcDmzSD+iaY09+4gw5AglGMr+1Cd0GlpjsUZUOHChQ0AlGN/Bqg9iMc4OsmG7ykBcmc8EfBRVL/Xj5Fs3BLL0cXjCoLkg7JLg52emb6lFmNTR8Otmu27N5rd2Ts5L9vbvJ5IbWSVTkzCruBcca6LObVlMI5HC4pirpr3c3H04LPyanC2odl9Rs+pRQwYCFGwyML6aObAtXYhvYGLknj16UC2AjRj4mBw0gw4v2PQKDxi2PaRE9QtkMv+rHHggLDbKuec2gWTzcPPiduN/R6L2+artfg2lDXckHfm/5JmbU2ObZK9/N4BViuuTdgxlMyRPg/OYBh6w0ZqKcCn0Yg+nloQj80XkwLBDRwOSuospEtuZNoISgfvvQ8me8kDw==
  template:
    metadata:
      creationTimestamp: null
      name: frigate-secrets
      namespace: frigate
