apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - services.yml
#  - serviceMonitors.yml
  - sealed-secrets.yml
  - deployments.yml
  - ingresses.yml
  - pv.yml
  - servicemonitors.yml
