---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jellyfin-pvc
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn
