---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jellyfin-pvc
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: jellyfin-pv
  storageClassName: longhorn
