---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cert-manager-secrets
  namespace: cert-manager
spec:
  encryptedData:
    CF_TOKEN: AgCpA3TZhb9OCJ7DcGyEVWBSr4MKy0Unoi1lVA4OoNjmVdMfkfczKZpu05P8VyqjxfcbHVdmzDMvRYBnK4sCBHq19YphcAy/HHj6vpVPq4Ntp2qKcNhuWdmut4Ng1kuxtRrROfjV+J0Sb6kyUQbyw+DpDYbPnbOBfPT7kMMB2/YIZ8C1GcK0/ITjfq1EmfbvyG8CZrcUELXLY0CsQ4VyaVA1gfdRNMY0NbVCqeiTdoJV5wgnxAG77dsTO8DrXacWEvHyRhJf9Sz73q8PSF800kqqL2AUL1I3L2IxbE/rdJ5Upwq4P9FxVbdkFGA4yaKwNx8YbveTpNZn/Bbk0dcdjm5Et4ynhKIxgk/upRLMzRLq7l8w5loDqHz+FI5815ECADJMQgp3pRgJwsCXz8tr9hUby/tSoI3jt5e2ZBSdGnn9nQxKGDNtQOH/VNGlwgwDcewCdZcc9stPTwcclghOmwwKGV5LMeYdLbcohe3KEMLj4ojdgSQwMKxnd+j4sqRvnarOBUAtuH/m73VlM/k3l7cmKfk69sWFszqLuc6bXA55D0qV/uQwUZIHbBJKVxhbTCJhJYhLhS15ZN682Yor9TSN0gfWtfDjDVH7Bi6uwouf4EtLV6yYAsJ1wipWMhlQA9zzabFOSKZp/2UYmhe03IIb/SaUnoYMJ66qfWhARj3N/ShBJsRaqDGUUxDk/4zVHlhLYKEUryOkGfa0SFHHRi2ap3RxyvyzphpGPq1BhsnGOevMKgUmaqWG
  template:
    metadata:
      creationTimestamp: null
      name: cert-manager-secrets
      namespace: cert-manager
    type: Opaque
