---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: registry
  namespace: registry
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`docker.cr.ryanb.tv`)
      kind: Rule
      services:
        - name: registry
          kind: Service
          port: http-dockerio
    - match: Host(`ghcr.cr.ryanb.tv`)
      kind: Rule
      services:
        - name: registry
          kind: Service
          port: http-ghcrio
    - match: Host(`quay.cr.ryanb.tv`)
      kind: Rule
      services:
        - name: registry
          kind: Service
          port: http-quayio
    - match: Host(`lscr.cr.ryanb.tv`)
      kind: Rule
      services:
        - name: registry
          kind: Service
          port: http-lscrio
  tls: {}
