apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  source:
    path: src/k8s/k8s.cr/argocd/resources/argocd
    repoURL: https://github.com/ryanbtv/homelab-foss.git
    targetRevision: main
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
    syncOptions:
      - CreateNamespace=true
