apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-driver-nfs
  namespace: argocd
spec:
  sources:
    - repoURL: https://github.com/ryanbtv/homelab-foss.git
      path: src/k8s/k8s.cr/argocd/resources/csi-driver-nfs
      targetRevision: main
    - repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
      chart: csi-driver-nfs
      targetRevision: v4.9.0
      helm:
        releaseName: csi-driver-nfs
  destination:
    namespace: csi-driver-nfs
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 5s
        maxDuration: 5m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
      # non-default capabilities (container "nfs" must not include "SYS_ADMIN" in securityContext.capabilities.add), host namespaces (hostNetwork=true), hostPath volumes (volume "pods-mount-dir"), privileged (container "nfs" must not set securityContext.privileged=true)
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
