---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/ryanbtv/homelab-foss.git
      path: src/k8s/k8s.cr/argocd/resources
      targetRevision: main
    - repoURL: https://helm.goharbor.io
      chart: harbor
      targetRevision: 1.16.2
      helm:
        releaseName: harbor
        valuesObject:
          externalURL: https://oci.ryanb.tv
          expose:
            type: loadBalancer
            tls:
              auto:
                commonName: oci.ryanb.tv
            loadBalancer:
              # The name of LoadBalancer service
              name: harbor
              # Set the IP if the LoadBalancer supports assigning IP
              IP: 10.1.50.34
          logLevel: debug
          containerSecurityContext:
            runAsUser: 1000
            runAsGroup: 1000
  destination:
    server: "https://kubernetes.default.svc"
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 5s
        maxDuration: 5m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
