---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-system
  namespace: argocd
spec:
  sources:
    - repoURL: https://github.com/ryanbtv/homelab-foss.git
      path: src/k8s/k8s.cr/argocd/resources/kube-system
      targetRevision: main
    - repoURL: https://democratic-csi.github.io/charts
      chart: snapshot-controller
      targetRevision: 0.2.4
      helm:
        releaseName: snapshot-controller

  destination:
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
    syncOptions:
      - CreateNamespace=true