apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry
  namespace: argocd
spec:
  sources:
    - repoURL: https://github.com/ryanbtv/homelab-foss.git
      path: src/k8s/k8s.cr/argocd/resources/registry
      targetRevision: main
  destination:
    namespace: registry
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 5s
        maxDuration: 5m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true