---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: traefik
  namespace: traefik
spec:
  jobLabel: serviceMonitor/ryanb.tv/traefik
  selector:
    matchLabels:
      mylabel/app: traefik
  endpoints:
  - port: metrics
    interval: 15s