---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "63.1.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
      interval: 12h
  values:
    kubeProxy:
      service:
        selector:
          component: kube-proxy
    prometheus:
      enabled: true
      server:
        persistentVolumeClaim:
          existingClaim: prometheus
      service:
        enabled: true
        loadBalancerIP: "10.1.50.130"
        type: LoadBalancer
    grafana:
      server:
        persistentVolumeClaim:
          existingClaim: grafana
      service:
        enabled: true
        loadBalancerIP: "10.1.50.132"
        type: LoadBalancer
      serviceMonitor:
        enabled: true
      persistence:
        type: pvc
        enabled: true
        existingClaim: grafana
