---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus
      version: "25.27.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
      interval: 12h
  values:
    server:
      persistentVolumeClaim:
        existingClaim: prometheus
      service:
        enabled: true
        loadBalancerIP: "10.1.50.130"
        type: LoadBalancer

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: prometheus
spec:
  interval: 30m
  chart:
    spec:
      chart: grafana
      version: "8.5.2"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 12h
  values:
    persistence:
      enabled: true
      existingClaim: grafana
    service:
      enabled: true
      loadBalancerIP: "10.1.50.132"
      type: LoadBalancer
    serviceMonitor:
      enabled: true
    admin:
      existingSecret: grafana-secrets
      userKey: user
      passwordKey: pass


---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-operator
  namespace: prometheus
spec:
  interval: 30m
  releaseName: grafana-operator
  chartRef:
    kind: OCIRepository
    name: grafana-operator
    namespace: flux-system

