---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "63.1.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
      interval: 12h
  values:
    kubeProxy:
      service:
        selector:
          component: kube-proxy
    prometheus:
      enabled: true
      windowsMonitoring:
        enabled: true
      service:
        enabled: true
        loadBalancerIP: "10.1.50.130"
        type: LoadBalancer
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 50Gi
        podMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
      externalUrl: https://prometheus.ryanb.tv
    alertmanager:
      enabled: true
      service:
        enabled: true
        loadBalancerIP: "10.1.50.131"
        type: LoadBalancer
      config:
        global:
          resolve_timeout: 1m
          slack_api_url: "https://hooks.slack.com/services/null"
        route:
          receiver: "slack-notifications"
          group_by:
            - job
        receivers:
          - name: "null"
          - name: "slack-notifications"
            slack_configs:
              - channel: "#alertmanager"
                send_resolved: true
                icon_url: https://avatars3.githubusercontent.com/u/3380462
                title: |-
                  [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
                  {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
                    {{" "}}(
                    {{- with .CommonLabels.Remove .GroupLabels.Names }}
                      {{- range $index, $label := .SortedPairs -}}
                        {{ if $index }}, {{ end }}
                        {{- $label.Name }}="{{ $label.Value -}}"
                      {{- end }}
                    {{- end -}}
                    )
                  {{- end }}
                text: >-
                  {{ range .Alerts -}}
                  *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

                  *Description:* {{ .Annotations.description }}

                  *Details:*
                    {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
                    {{ end }}
                  {{ end }}
      alertmanagerSpec:
        replicas: 1
        storage:
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 5Gi
      externalUrl: https://alertmanager.ryanb.tv
    grafana:
      replicas: 1
      service:
        enabled: true
        loadBalancerIP: "10.1.50.132"
        type: LoadBalancer
      persistence:
        type: pvc
        enabled: true
      adminUser: admin
      adminPassword: admin
