---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: node-feature-discovery-hooks-pre
  namespace: flux-system
spec:
  dependsOn: []
  path: ./src/fluxcd/infra/node-feature-discovery/hooks-pre
  targetNamespace: node-feature-discovery 
  # Standard Params:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-resources
  prune: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: node-feature-discovery-assets
  namespace: flux-system
spec:
  dependsOn:
    - name: node-feature-discovery
  path: ./src/fluxcd/infra/node-feature-discovery/assets
  targetNamespace: node-feature-discovery 
  # Standard Params:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-resources
  prune: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: node-feature-discovery-hooks-post
  namespace: flux-system
spec:
  dependsOn:
    - name: node-feature-discovery
  path: ./src/fluxcd/infra/node-feature-discovery/node-feature-discovery/hooks-post
  targetNamespace: node-feature-discovery 
  # Standard Params:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-resources
  prune: true
