---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgAqDs3fI7yggYE32ivjXvLS39BcP55v7ugICHeRDXRaqrWw1OTnp8zMr32Ui0AthP9NWEMu1MYUp6DWJzTqqpfkkhFdh7ROCZwO46OMrnZCd+/ETEdJhuE4xVH3QhsqxOZ2NwffkmZoVIiQPM6eI6gTNQr0husvLviCl+BYxCxQtqeL/iWfd0PVta472MqVy5iUD+7f2YhA58Qhl9JgjTvxOdDywjyOflTKV/wG0CVe9M71UpWVcumxvE2TaLZ+RrxejdddH6FD9WSt8z6PTgru/iaxOx64IG0lms9VbgjpN70nkdX/KNrp6lm3urbxOj8VQa79yLFVccUuqXZuJkmCnCTgz+DhyOiuFiMGdUTNBPZThvI1/pe7Ut1VRSpWrVYAU6dAWgsm5ips3MF3gaY2atsHNH739U6HxsOH3z4nZDYYAFlQMN33woja8dOAJE2t20w8yF9tKOMHCacH8KtDZRPyeMaJW4DFQYkXiF+XkGkWHL/7/XVn7TD5EPf+s+og6PfNHdIyanF1PJwb1RApzfM6ORp9HFcZq9qtUAt1tV4AxL5Y2rQ0QUMgyK1bEzxoFc3y1buFdM/8Hlblq98gesq0kwjq2Iho9wuFMkmhocumLlm+hiWYPHtxilC3fz/gzsKSBD5HfYPb/SnA6pPY+6cVMeYzkHnhrEaf9AWy00dntv04+5bMGOLEAHB/1GxA+RC23weqq0nNjaKxpqbgHHVwcm53sdCjF8aW/nk=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-token
      namespace: flux-system
