---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: s3-csi
  namespace: flux-system
spec:
  dependsOn:
    - name: sealed-secrets-assets # CloudFlare API Token
  path: ./src/fluxcd/infra/s3-csi
  # Standard Params:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-resources
  prune: true
