---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: s3-csi
  namespace: s3-csi
spec:
  interval: 30m
  chart:
    spec:
      chart: aws-mountpoint-s3-csi-driver
      version: "1.9.0"
      sourceRef:
        kind: HelmRepository
        name: s3-csi
        namespace: flux-system
      interval: 12h
