apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsync
  labels:
    app.kubernetes.io/name: rsync
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: rsync
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rsync
    spec:
      containers:
      - name: rsync
        image: axiom/rsync-server:latest
        env:
          - name: USERNAME
            value: admin
          - name: PASSWORD
            value: password
          - name: VOLUME
            value: /data
        ports:
          - containerPort: 873
            name: rsync
            protocol: TCP
        volumeMounts:
          - name: data
            mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: rsync-pvc
      dnsConfig:
        options:
          - name: ndots
            value: "1"