---
apiVersion: v1
kind: Service
metadata:
  name: rsync
  labels:
    ryanb.tv/app: rsync
spec:
  selector:
    app.kubernetes.io/name: rsync
  ports:
  - name: rsync
    protocol: TCP
    port: 873
    targetPort: rsync
  type: LoadBalancer
  loadBalancerIP: 10.1.50.140