apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cloudflared
  namespace: cloudflared
  labels:
    app.kubernetes.io/name: cloudflared
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflared
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: docker.io/cloudflare/cloudflared
        command: [
          "cloudflared",
          "tunnel", 
          "--no-autoupdate",
          "--metrics",
          "0.0.0.0:9100",
          "run",
          ]
        env:
        - name: TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflared-secrets
              key: CF_TOKEN
        ports:
        - containerPort: 9100
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            # Cloudflared has a /ready endpoint which returns 200 if and only if
            # it has an active connection to the edge.
            path: /ready
            port: 9100
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
      dnsConfig:
        options:
          - name: ndots
            value: "1"