---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflared
  namespace: flux-system
spec:
  dependsOn:
    - name: sealed-secrets-assets # CloudFlare API Token
    - name: prometheus-assets # ServiceMonitors
  path: ./src/fluxcd/infra/cloudflared/assets
  targetNamespace: cloudflared 
  # Standard Params:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-resources
  prune: true
