---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  jobLabel: serviceMonitor/ryanb.tv/cloudflared
  selector:
    matchLabels:
      mylabel/app: cloudflared
  endpoints:
  - port: prometheus
    interval: 15s