---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-kustomizations
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://github.com/ryanbtv/homelab-foss
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include only app/infra top-level flux-kustomizations.yml files:
    !/src/fluxcd/**/flux-kustomizations.yml

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-kustomizations
  namespace: flux-system
spec:
  path: ./src/fluxcd/
  targetNamespace: flux-system
  # Standard Params:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-kustomizations
  prune: true
