---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-resources
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://github.com/ryanbtv/homelab-foss
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include deploy dirs
    !/src/fluxcd/apps
    !/src/fluxcd/infra
    # Exclude previously-deployed resources:
    /src/fluxcd/**/namespaces.yml
    /src/fluxcd/**/helmRepository.yml

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-infra
  namespace: flux-system
spec:
  dependsOn:
  - name: flux-namespaces
  - name: flux-helmrepositories
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-resources
  path: ./src/fluxcd/infra
  prune: true
  wait: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-apps
  namespace: flux-system
spec:
  dependsOn:
  - name: flux-namespaces
  - name: flux-helmrepositories
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-resources
  path: ./src/fluxcd/apps
  prune: true
  wait: true