---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: emqx
  namespace: flux-system
spec:
  dependsOn:
    - name: prometheus
    - name: metallb
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: homelab-foss  
  prune: true
  path: ./src/fluxcd/apps/emqx

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: emqx-assets
  namespace: flux-system
spec:
  dependsOn:
    - name: emqx
    - name: sealed-secrets
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: homelab-foss  
  prune: true
  path: ./src/fluxcd/apps/emqx-assets
