---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: netbox
  namespace: flux-system
spec:
  dependsOn:
    - name: traefik
    - name: longhorn
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: homelab-foss  
  prune: true
  path: ./src/fluxcd/apps/netbox

