---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: emqx-assets
  namespace: flux-system
spec:
  dependsOn:
    - name: prometheus-assets
    - name: metallb-assets
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-resources
  prune: true
  path: ./src/fluxcd/apps/emqx/assets

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: emqx-hooks-post
  namespace: flux-system
spec:
  dependsOn:
    - name: emqx-assets
    - name: sealed-secrets
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-resources
  prune: true
  path: ./src/fluxcd/apps/emqx/hooks-post
