---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: emqx
  namespace: emqx
spec:
  interval: 30m
  chart:
    spec:
      chart: emqx-operator
      version: 2.2.24
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: emqx
      interval: 12h
  values:
    replicaCount: 4