---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: harbor
  namespace: harbor
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`oci.ryanb.tv`)
      kind: Rule
      services:
        - name: harbor
          kind: Service
          port: http-web
  tls: {}
