---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
  name: harbor-storage-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: csi-driver-nfs
  mountOptions:
    - nfsvers=4.2
  csi:
    driver: nfs.csi.k8s.io
    # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: 10.1.60.6/mnt/hdd/k8s/k8s.cr
    volumeAttributes:
      server: 10.1.60.6
      share: /mnt/hdd/k8s/k8s.cr
      subPath: harbor-storage

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: harbor-storage-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: harbor-storage-pv
  storageClassName: csi-driver-nfs

---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
  name: harbor-database-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: csi-driver-nfs
  mountOptions:
    - nfsvers=4.2
  csi:
    driver: nfs.csi.k8s.io
    # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: 10.1.60.6/mnt/hdd/k8s/k8s.cr
    volumeAttributes:
      server: 10.1.60.6
      share: /mnt/hdd/k8s/k8s.cr
      subPath: harbor-database

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: harbor-database-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: harbor-database-pv
  storageClassName: csi-driver-nfs