---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: datashim
  namespace: datashim
spec:
  interval: 30m
  chart:
    spec:
      chart: datashim-charts
      version: "0.4.0"
      sourceRef:
        kind: HelmRepository
        name: datashim
        namespace: flux-system
      interval: 12h
  install:
    createNamespace: true