---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-secrets
  namespace: cloudflared
spec:
  encryptedData:
    CF_TOKEN: AgB+NXhskNMyO2HXMnZkTxPzJOZvXuaz5DJ2tvb3MVDGYHabtHDNeAWJp/AmZXpkKGjGcann0RYi7A/FCIN3GGMfA0s/lWgVyYBlRnhYI+F5f2G1RSacFgbAuokjskkN3n/3sZPgzHNBdNKqvv5KdjfQEtxrk9IRfxWb2fXikmLJUdRYSnFyKAczNz45u6jDIKMRiaQqApNjWhM1r5xNq5QfYADsy6Td6Pqc5YAu2jcKKpfSRNqBeR3h/Lk2VBbVQKdd2cUdQQk8/tYiKQr0mEXCZKvndFLa54vWn1szEeITmJoNP/mcggSy+w9zP4O7PuS9tmn1mGZ9o5M1V/7i6thqnxCAOGL2rG/wwzqnjfSSqR7q38c6NC9+V2L7cftoJKtwMMTw8n++9y/QmSNUbEZRtR7XoQar5HIsDii+pn8epOuDdJhSledTDL0HwOqKcgTiq4YguKU41QFzHLZeeifTIhRurpFztw28IGrLeOOt1PARRytLQVJnXOUKzvSaKre5AVDaE+tg5tXShIqSVTWUtqY7aSsW4M1QS6sy9drihOB2LGRw8ElI5HeaTG6N+y48o3NAz/RauBsvMlgoM0iU2lnehmB1LqvABYjv+yKLXDyi52tC3VL7xaO6ZR9l/+bgbCYrsCe0zWbIzceIWF1C3cXBDJWLVn6IcpZ7Vs8+dtVGnRUkb85Oz6ewsRZ6htMuc1GWuipO3tHfGrSBbn3ZGzUOjJc+Nr6XSEuGWdbJa2vZoZLfkuvfGa/PumBzSjc33Rr01i3C9ARGcsWFpdfv78xb6TNwyFKBziQ5p8zXTHf+mcuv+67edJp9mUHJHvVX/h1E6IUk2kSx8TPxfi7zB8nWCGSq7EJtqdUWsQSiq8ZRLMhdCzDjFpk0xUh2mIme4crjAqkGK/G4zdYmvjUN+Qr4c+FaESIVWR15ZfbZ2p4NBjaP+/G8
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-secrets
      namespace: cloudflared
