---
apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx
  namespace: emqx
spec:
  image: emqx:5.5.0
  coreTemplate:
    spec:
      replicas: 3
      env:
      - name: EMQX_MQTT__MAX_PACKET_SIZE
        value: 256MB
  bootstrapAPIKeys:
    - secretRef:
        key:
          secretName: emqx-secret
          secretKey: api_key
        secret:
          secretName: emqx-secret
          secretKey: api_secret
  replicantTemplate:
    spec:
      replicas: 3
      env:
      - name: EMQX_MQTT__MAX_PACKET_SIZE
        value: 256MB
  listenersServiceTemplate:
    spec:
      type: LoadBalancer
      loadBalancerIP: 10.1.50.136
  dashboardServiceTemplate:
    metadata:
      labels:
        ryanb.tv/app: emqx
    spec:
      type: LoadBalancer
      loadBalancerIP: 10.1.50.137
