---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb
spec:
  interval: 30m
  chart:
    spec:
      chart: metallb
      version: "0.14.8"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      interval: 12h
  values:
##### TODO: Deploy these after Prometheus is deployed ####
#    prometheus:
#      podMonitor:
#        enabled: true
#      prometheusRule:
#        enabled: true
    speaker:
      frr:
        enabled: true
    crds:
      enabled: true