---
services:
  app:
    image: ghcr.io/blakeblackshear/frigate:0.14.1
    privileged: true # this may not be necessary for all setups
    cap_add:
      - CAP_PERFMON
    runtime: nvidia
    shm_size: "2048mb"
    environment:
    - TZ=America/Chicago
    - PLUS_API_KEY=${PLUS_API_KEY}
    volumes:
      # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/apex_0:/dev/apex_0 
      - /dev/apex_1:/dev/apex_1 
      - frigate:/config
      - /ssd/frigate:/media/frigate
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    labels:
      - traefik.enable=true
      - traefik.http.routers.frigate.rule=Host(`nvr.ff.lan`)
      - traefik.http.routers.frigate.tls=true
      - traefik.http.services.frigate.loadbalancer.server.port=5000

  prometheus_exporter:
    image: docker.io/rhysbailey/prometheus-frigate-exporter:0.1.1
    environment:
    - FRIGATE_STATS_URL=http://docker.ff.lan:5000/api/stats
    restart: always
    networks:
      - main

networks:
  main:
    name: main
    external: true

volumes:
  frigate: