---
services:
  db:
    image: docker.io/library/mongo:6.0.18
    hostname: graylog-db
    ports:
      - "27017:27017"   
    restart: "on-failure"
    networks:
      - main
    volumes:
      - "graylog-db-data:/data/db"
      - "graylog-db-config:/data/configdb"  

  datanode:
    image: docker.io/graylog/graylog-datanode:6.1
    hostname: graylog-datanode
    environment:
      GRAYLOG_DATANODE_NODE_ID_FILE: "/var/lib/graylog-datanode/node-id"
      GRAYLOG_DATANODE_PASSWORD_SECRET: "somepasswordpepper"
      GRAYLOG_DATANODE_ROOT_PASSWORD_SHA2: ${ROOT_PASSWORD_SHA2}
      GRAYLOG_DATANODE_MONGODB_URI: "mongodb://graylog-db-1:27017/graylog"
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "8999:8999/tcp"   # DataNode API
      - "9200:9200/tcp"
      - "9300:9300/tcp"
    networks:
      - main  
    volumes:
      - "graylog-datanode:/var/lib/graylog-datanode"
    restart: "always"  

  # Graylog: https://hub.docker.com/r/graylog/graylog/
  app:
    image: docker.io/graylog/graylog:6.1
    hostname: graylog-app
    depends_on:
      db:
        condition: "service_started"
      datanode:
        condition: "service_started"
    entrypoint: "/usr/bin/tini -- /docker-entrypoint.sh"
    environment:
      GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/config/node-id"
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      GRAYLOG_MONGODB_URI: "mongodb://graylog-db-1:27017/graylog"
      # To make reporting (headless_shell) work inside a Docker container
      GRAYLOG_REPORT_DISABLE_SANDBOX: "true"
      # CHANGE ME (must be at least 16 characters)!
      GRAYLOG_PASSWORD_SECRET: "somepasswordpepper"
      # Password: "admin"
      GRAYLOG_ROOT_PASSWORD_SHA2: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
      GRAYLOG_HTTP_EXTERNAL_URI: "https://logs.ff.lan/"
    ports:
      # Graylog web interface and REST API
      - "9000:9000/tcp"
      # Beats
      - "5044:5044/tcp"
      # Syslog TCP
      - "5140:5140/tcp"
      # Syslog UDP
      - "5140:5140/udp"
      # GELF TCP
      #- "12201:12201/tcp"
      # GELF UDP
      #- "12201:12201/udp"
      # Forwarder data
      #- "13301:13301/tcp"
      # Forwarder config
      #- "13302:13302/tcp"
    restart: "always"
    labels:
      - traefik.enable=true
      - traefik.http.routers.graylog.rule=Host(`logs.ff.lan`)
      - traefik.http.routers.graylog.tls=true
      - traefik.http.routers.graylog.tls.certresolver=hcv
      - traefik.http.services.graylog.loadbalancer.server.port=9000
    networks:
      - main
    volumes:
      - "graylog-data:/usr/share/graylog/data"

networks:
  main:
    name: main
    external: true

volumes:
  graylog-db-data:
  graylog-db-config:
  graylog-datanode:
  graylog-data: