---
services:
  db:
    image: mariadb:10
    command:
      - mysqld
      - --innodb-file-per-table=1
      - --lower-case-table-names=0
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - librenms_db:/var/lib/mysql
    environment:
      - TZ=America/Chicago
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=librenms
      - MYSQL_USER=librenms
      - MYSQL_PASSWORD=librenms
    restart: always

  redis:
    image: redis:7.2-alpine
    environment:
      - TZ=America/Chicago
    restart: always

  app:
    image: librenms/librenms:24.11.0
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
    depends_on:
      - db
      - redis
    volumes:
      - librenms:/data
    environment:
      - TZ=America/Chicago
      - PUID=1000
      - PGID=1000
      - DB_HOST=librenms-db-1
      - DB_NAME=librenms
      - DB_USER=librenms
      - DB_PASSWORD=librenms
      - DB_TIMEOUT=60
      - MEMORY_LIMIT=256M
      - MAX_INPUT_VARS=1000
      - UPLOAD_MAX_SIZE=16M
      - OPCACHE_MEM_SIZE=128
      - REAL_IP_FROM=0.0.0.0/0
      - REAL_IP_HEADER=X-Forwarded-For
      - LOG_IP_VAR=remote_addr
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - REDIS_HOST=librenms-redis-1
      - LIBRENMS_SNMP_COMMUNITY=nms
      - LIBRENMS_WEATHERMAP=false
    restart: always

  dispatcher:
    image: librenms/librenms:24.11.0
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - app
      - redis
    volumes:
      - librenms:/data
    environment:
      - TZ=America/Chicago
      - PUID=1000
      - PGID=1000
      - DB_HOST=librenms-db-1
      - DB_NAME=librenms
      - DB_USER=librenms
      - DB_PASSWORD=librenms
      - DB_TIMEOUT=60
      - DISPATCHER_NODE_ID=dispatcher1
      - SIDECAR_DISPATCHER=1
      - MEMORY_LIMIT=256M
      - MAX_INPUT_VARS=1000
      - UPLOAD_MAX_SIZE=16M
      - OPCACHE_MEM_SIZE=128
      - REAL_IP_FROM=0.0.0.0/0
      - REAL_IP_HEADER=X-Forwarded-For
      - LOG_IP_VAR=remote_addr
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - REDIS_HOST=librenms-redis-1
      - LIBRENMS_SNMP_COMMUNITY=nms
      - LIBRENMS_WEATHERMAP=false
    restart: always

  syslogng:
    image: librenms/librenms:24.11.0
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - app
      - redis
    ports:
      - target: 514
        published: 514
        protocol: tcp
      - target: 514
        published: 514
        protocol: udp
    volumes:
      - librenms:/data
    environment:
      - TZ=America/Chicago
      - PUID=1000
      - PGID=1000
      - DB_HOST=librenms-db-1
      - DB_NAME=librenms
      - DB_USER=librenms
      - DB_PASSWORD=librenms
      - DB_TIMEOUT=60
      - SIDECAR_SYSLOGNG=1
      - MEMORY_LIMIT=256M
      - MAX_INPUT_VARS=1000
      - UPLOAD_MAX_SIZE=16M
      - OPCACHE_MEM_SIZE=128
      - REAL_IP_FROM=0.0.0.0/0
      - REAL_IP_HEADER=X-Forwarded-For
      - LOG_IP_VAR=remote_addr
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - REDIS_HOST=librenms-redis-1
      - LIBRENMS_SNMP_COMMUNITY=nms
      - LIBRENMS_WEATHERMAP=false
    restart: always

  snmptrapd:
    image: librenms/librenms:24.11.0
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - app
      - redis
    ports:
      - target: 162
        published: 162
        protocol: tcp
      - target: 162
        published: 162
        protocol: udp
    volumes:
      - librenms:/data
    environment:
      - TZ=America/Chicago
      - PUID=1000
      - PGID=1000
      - DB_HOST=librenms-db-1
      - DB_NAME=librenms
      - DB_USER=librenms
      - DB_PASSWORD=librenms
      - DB_TIMEOUT=60
      - SIDECAR_SNMPTRAPD=1
      - MEMORY_LIMIT=256M
      - MAX_INPUT_VARS=1000
      - UPLOAD_MAX_SIZE=16M
      - OPCACHE_MEM_SIZE=128
      - REAL_IP_FROM=0.0.0.0/0
      - REAL_IP_HEADER=X-Forwarded-For
      - LOG_IP_VAR=remote_addr
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - REDIS_HOST=librenms-redis-1
      - LIBRENMS_SNMP_COMMUNITY=nms
      - LIBRENMS_WEATHERMAP=false
    restart: always

volumes:
  librenms:
  librenms_db: