---
services:
  db:
    image: mariadb:10
    command:
      - mysqld
      - --innodb-file-per-table=1
      - --lower-case-table-names=0
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - librenms_db:/var/lib/mysql
    environment:
      - TZ=America/Chicago
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=librenms
      - MYSQL_USER=librenms
      - MYSQL_PASSWORD=librenms
    restart: always
    networks:
      - main

  redis:
    image: redis:7.2-alpine
    environment:
      - TZ=America/Chicago
    restart: always
    networks:
      - main

  app:
    image: librenms/librenms:24.11.0
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - db
      - redis
    volumes:
      - librenms:/data
    environment:
      - DB_HOST=librenms-db-1
      - DB_NAME=librenms
      - DB_USER=librenms
      - DB_PASSWORD=librenms
      - DB_TIMEOUT=60
      - MAX_INPUT_VARS=1000
      - REAL_IP_FROM=0.0.0.0/0
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - REDIS_HOST=librenms-redis-1
      - LIBRENMS_SNMP_COMMUNITY=nms
      - LIBRENMS_WEATHERMAP=false
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.nms.rule=Host(`nms.ff.lan`)
      - traefik.http.routers.nms.tls=true
      - traefik.http.services.nms.loadbalancer.server.port=8000
    networks:
      - main

  dispatcher:
    image: librenms/librenms:24.11.0
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - app
      - redis
    volumes:
      - librenms:/data
    environment:
      - DB_HOST=librenms-db-1
      - DB_NAME=librenms
      - DB_USER=librenms
      - DB_PASSWORD=librenms
      - DB_TIMEOUT=60
      - DISPATCHER_NODE_ID=dispatcher1
      - SIDECAR_DISPATCHER=1
      - MAX_INPUT_VARS=1000
      - REAL_IP_FROM=0.0.0.0/0
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - REDIS_HOST=librenms-redis-1
      - LIBRENMS_SNMP_COMMUNITY=nms
      - LIBRENMS_WEATHERMAP=false
    restart: always
    networks:
      - main

  syslogng:
    image: librenms/librenms:24.11.0
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - app
      - redis
    ports:
      - target: 514
        published: 514
        protocol: tcp
      - target: 514
        published: 514
        protocol: udp
    volumes:
      - librenms:/data
    environment:
      - DB_HOST=librenms-db-1
      - DB_NAME=librenms
      - DB_USER=librenms
      - DB_PASSWORD=librenms
      - DB_TIMEOUT=60
      - SIDECAR_SYSLOGNG=1
      - MAX_INPUT_VARS=1000
      - REAL_IP_FROM=0.0.0.0/0
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - REDIS_HOST=librenms-redis-1
      - LIBRENMS_SNMP_COMMUNITY=nms
      - LIBRENMS_WEATHERMAP=false
    restart: always
    networks:
      - main

  snmptrapd:
    image: librenms/librenms:24.11.0
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - app
      - redis
    ports:
      - target: 162
        published: 162
        protocol: tcp
      - target: 162
        published: 162
        protocol: udp
    volumes:
      - librenms:/data
    environment:
      - DB_HOST=librenms-db-1
      - DB_NAME=librenms
      - DB_USER=librenms
      - DB_PASSWORD=librenms
      - DB_TIMEOUT=60
      - SIDECAR_SNMPTRAPD=1
      - MAX_INPUT_VARS=1000
      - REAL_IP_FROM=0.0.0.0/0
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - REDIS_HOST=librenms-redis-1
      - LIBRENMS_SNMP_COMMUNITY=nms
      - LIBRENMS_WEATHERMAP=false
    restart: always
    networks:
      - main

networks:
  main:
    name: main
    external: true

volumes:
  librenms:
  librenms_db: