---
services:
  app:
    image: docker.io/croc/unimus:2.6.0
    environment:
      - JAVA_OPTS=-Xms256M -Xmx1024M -Dunimus.core.connect-timeout=20000 -Dunimus.core.inter-connection-delay=1000 -Dunimus.core.cli-expect-timeout=30000
      - TZ=America/Chicago
    volumes:
      - unimus:/etc/unimus
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.unimus.rule=Host(`unimus.ff.lan`)
      - traefik.http.routers.unimus.tls=true
      - traefik.http.services.unimus.loadbalancer.server.port=8085
    networks:
      - main

networks:
  main:
    name: main
    external: true

volumes:
  unimus: