---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-hooks-pre
  namespace: flux-system
spec:
  dependsOn: []
  path: ./src/fluxcd/infra/cert-manager/hooks-pre
  targetNamespace: cert-manager 
  # Standard Params:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-app-assets
  prune: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-assets
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager-hooks-pre
  path: ./src/fluxcd/infra/cert-manager/assets
  targetNamespace: cert-manager
  # Standard Params:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-resources
  prune: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-hooks-post
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
    - name: sealed-secrets
  path: ./src/fluxcd/infra/cert-manager/hooks-post
  targetNamespace: cert-manager 
  # Standard Params:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-resources
  prune: true
