---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmRelease.yml
  - helmRepository.yml
  - namespace.yml
  - certificates.yml
  - clusterissuers.yml
  - sealed-secrets.yml