---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-secret
  namespace: kube-system
spec:
  encryptedData:
    access_ky: AgBJlfWCl9rkiWPRoYuxvktsXwM4RG5OKvM9lgMtAIWW9u59hmpV1P1uNzZ6xqGKsrzpDVdJRijprXSGGg+mTVGECDC78qpWhWCvYmdUcpcHSPeEy1A5ljttIoE5R54DTgOwIxFbP1HiPoWMX2tWvmCYL1Et3mOGAx4s98qyasW2nwORvkpLGh2VNMYSGbATIWFFnb4HdlP/gx4FN1kBOvotoxoONaa1qirJg5z+0c01wF/G71DYaFLK/gDiys+wYqInjXMph75HfP5r7B+DUq7y6f5xTosxfKpt9kWaRllJ7AmzGQQ/oe68BtOeYe1oBKrHT4zoXMCuP97t3H3VHjLilx1TWuOFHIbAxdeogtrB+/rbe+MQ99I0bQKHbb6xhIDl0UZOSIHqZAcBoN42mqKY+4zXu8a7tDQaBvYzqID5tTxzZpQp8M5AqJk7jIC1yKFK3WOJM/9JXdDeFClGIQNEwzoM5GldargZ+15lNVcI5RhW8X8Ulrd7pMh942823xscAI9sx/7IeCrbNNyDpfuW+Jnkd53Pk+6vv/smvV+tcAYz15FGKMRyWK5dY/QmrxPo/kEMxIgs6PxzgkZgJugtqp6VUYgBhWdh0EIFt97KwJvmjrNFaTsaEh8B2aHQU2PLj73arojBCso9qq/UhSZEVjpkLQyJ9VePCPXjImWJJ4wSRR5+sq2xhKg7jJ1Xkf5UnOT4VxFUcg==
    key_id: AgCVwSoTgbI9GGQm8EuVisBN3TKpCLQQ4EvYSNFgPHJbsgDn6pthrzLauHWUlejeH8NiVm3PrIPrFkiUvtNzZlDwtv0rvimNaII0cWg+AbEMQ3Ln2aa92nBRH9fpDsG5Tv4iXYRHVa3hp4+lhIWiUOT8oYPw8Ll51dLkjnIvSX9eogVmquyowl+X8LSw+fIALPu0YNKYC2j7crzeipSkPea1XeHUzKRDDvg2/o+nBBK0mB+2hbZGvYb1MshoV9N21+dUwii/N69x4PTyMgJVLc9Nr7XrbiaFZTKLHTu4yfuclMmy37i7bKru1RVFzc/iGuZPUiW6ShjTETG0zs1txvZ8PnV8HExSySSWCcoLLCVvdS/LYs04ByO/Z0xxNG8uWAKvGrFNAOdv6MwyoHwAnh9HpgXHDRruVmDQj61NBachYLSYObcWoTRlcrzMZ72BFyYv7F9QJtsWKX9jcEQKBLaLCfIy/L+4AMbiF9SapBw11zvPOUzy14M8dbDX5dspJov60iuL2cK5K6u8VE80LMN1/B/ITZb7o0t3Ev3JKOBXGPX808TEZ67CAEp6E9bibw1lqqpz++vzInFrwLtUeITkA/mS1SQSjZM0hNE1dbixr1t19R8aQ3ftlLHOsjEmi2uCWCJ3wKr/VDTsxiD6Vla+dMZ4JZ06aS+tP0Z4V5495pNS0YB6DMOGAUXJzVCbS9oBVN7M7w==
  template:
    metadata:
      creationTimestamp: null
      name: aws-secret
      namespace: kube-system
