---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-hooks-pre
  namespace: flux-system
spec:
  dependsOn: []
  path: ./src/fluxcd/infra/metallb/hooks-pre
  targetNamespace: metallb 
  # Standard Params:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-resources
  prune: true
  # Resources required to consider the Kustomization "healthy"
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: bfdprofiles.metallb.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: bgpadvertisements.metallb.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: bgppeers.metallb.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: communities.metallb.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: ipaddresspools.metallb.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: l2advertisements.metallb.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: servicel2statuses.metallb.io

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-assets
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb-hooks-pre
  path: ./src/fluxcd/infra/metallb/assets
  targetNamespace: metallb 
  # Standard Params:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-resources
  prune: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-hooks-post
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb-assets
  path: ./src/fluxcd/infra/metallb/metallb/hooks-post
  targetNamespace: metallb 
  # Standard Params:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-resources
  prune: true
