---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: postgres-operator
spec:
  interval: 24h
  url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: postgres-operator-ui
spec:
  interval: 24h
  url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator-ui
