apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cr-ryanbtv-prod-cert
  namespace: default
spec:
  secretName: cr-ryanbtv-prod-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.cr.ryanb.tv"
  dnsNames:
  - "*.cr.ryanb.tv"
