---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-hooks-pre
  namespace: flux-system
spec:
  dependsOn: []
  path: ./src/fluxcd/infra/prometheus/hooks-pre
  targetNamespace: prometheus 
  # Standard Params:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-resources
  prune: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-assets
  namespace: flux-system
spec:
  dependsOn:
    - name: prometheus
  path: ./src/fluxcd/infra/prometheus/assets
  targetNamespace: prometheus 
  # Standard Params:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-resources
  prune: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-hooks-post
  namespace: flux-system
spec:
  dependsOn:
    - name: prometheus
  path: ./src/fluxcd/infra/prometheus/prometheus/hooks-post
  targetNamespace: prometheus 
  # Standard Params:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-resources
  prune: true
