---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: codeprojectai-assets
  namespace: flux-system
spec:
  dependsOn:
    - name: node-feature-discovery-hooks-post # nvidia
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-resources
  prune: true
  path: ./src/fluxcd/apps/codeprojectai/assets
  targetNamespace: codeprojectai 

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: codeprojectai-hooks-post
  namespace: flux-system
spec:
  dependsOn:
    - name: codeprojectai-assets
    - name: traefik-hooks-post # IngressRoute
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-resources
  prune: true
  path: ./src/fluxcd/apps/codeprojectai/hooks-post
  targetNamespace: codeprojectai 
